### ISSUE TITLE
Fix XSLT Transformation in Drupal 

### ISSUE THREAD

**Issue by ClemensBeck** [slub/dlf-3d-viewers#23]
* [x] @thedworak FIx XSLT Transformation from Mainz Repo to DFG 3D-Viewer Repo 
Additional information (see https://github.com/thedworak/dfg_3dviewer/issues/63)
"It's still open. For new entries, XML export is created, but not XSLT transformation. Or maybe it's save in the other way than before @thedworak need to confirm.
Example:
XML before: https://3d-repository.hs-mainz.de/export_xml_single/1626/
XSLT before: https://3d-repository.hs-mainz.de/sites/default/files/xml_structure/1626.xml

XML now: https://3d-repository.hs-mainz.de/export_xml_single/5293/
XSLT now: https://3d-repository.hs-mainz.de/sites/default/files/xml_structure/5293.xml (not working)

**Comment by thedworak** [comment]
Debugging let me discover a problem with the certificates when connecting locally
![image](https://github.com/user-attachments/assets/2f90cb1a-4412-4520-8824-a853f3e3844c)

**Comment by ClemensBeck** [comment]
I think @igorbajena has to renex the certificate?

**Comment by ClemensBeck** [comment]
@thedworak said he fixed it. Could you please check, @igorbajena?

**Comment by igorbajena** [comment]
I confirm that XSLT transformation is working now. The are two other things related to the problem:

1) All entries in repository for which XSLT was not created until now need to be open in edit mode and save again. Otherwise, the XSLT translation is not triggered.
2) Link to DFG 3D-Viewer demo is not working properly. For old entries it load wrong model, for new ones it creates link wrongly (but metadata are good). 
**Example of old entry:**
3D Repository Link: https://3d-repository.hs-mainz.de/wisski/navigate/552/view
![image](https://github.com/user-attachments/assets/689035ec-6c3b-4f30-b13e-42ef3408572d)
XSLT: https://3d-repository.hs-mainz.de/sites/default/files/xml_structure/552.xml
DFG 3D-Viewer demo: https://3dtest.dfg-viewer.de/viewer?tx_dlf%5Bid%5D=https%3A//3d-repository.hs-mainz.de/sites/default/files/xml_structure/552.xml&no_cache=1
![image](https://github.com/user-attachments/assets/5b8de57e-1627-4d4b-a1df-7840af4eae20)

**Example of new entry**
3D Repository Link: https://3d-repository.hs-mainz.de/wisski/navigate/5223/view
![image](https://github.com/user-attachments/assets/652174c0-c770-4288-bf2c-5ae854c26000)
XSLT: https://3d-repository.hs-mainz.de/sites/default/files/xml_structure/5223.xml
DFG 3D-Viewer demo: https://3d-repository.hs-mainz.de/viewer?tx_dlf%5Bid%5D=https%3A//3d-repository.hs-mainz.de/sites/default/files/xml_structure/5223.xml%26no_cache%3D1
![image](https://github.com/user-attachments/assets/c08c8e4e-a938-448c-998d-8164d1faee93)

For new ones I need to modify ho URL is crated, but first I would need to know if wrong model load is related to not creating URL properly or maybe it's issue of the DFG 3D-Viewer itself. The question is also if demo is still necessary and if it is worth to put more effort into it.

**Comment by igorbajena** [comment]
I checked the link with sample from Sander, but it still doesn't work. Then I investigate the XSLT transformation and it seems like link to 3d file is not there:

<mets:fileSec>
<mets:fileGrp USE="DEFAULT">
<mets:file ID="FILE_0001_DEFAULT" MIMETYPE="model/gltf-binary">
<mets:FLocat LOCTYPE="URL" xlink:href=""/>


Parameter "xlink:href" in last line doesn't have a value. @thedworak can you check why link to glb file is not generated in XSLT?

**Comment by thedworak** [comment]
Now I regenerated the XSLT file for objects with id 2, 3 and 42 and works out-of-the-box

**Comment by thedworak** [comment]
```
    <mets:fileGrp USE="THUMBS">
      <mets:file ID="FILE_0001_THUMBS" MIMETYPE="image/jpeg">
        <mets:FLocat LOCTYPE="URL" xlink:href="https://3d-repository.hs-mainz.de/sites/default/files/styles/wisski_preview/public/2022-06/Sy_Zabludow_model_skp_ZIP/views/Sy_Zabludow_model_skp_side45.png.jpg"/>
      </mets:file>
    </mets:fileGrp>
```

**Comment by ClemensBeck** [comment]
XSLT Transformation was fixed by @thedworak
